### PR TITLE
perf: replace array with map

### PR DESCRIPTION
**Pull request by JerrysShan**
## Description
Save the internal handlers and services and replace the array with map to improve performance

## Benchmark
```javascript
const Benchmark = require('benchmark');
const typedi = require('typedi');
// perf-20210707
const typedi2 = require('../typedi/build/cjs');

const suite = new Benchmark.Suite();
for (let i = 0; i < 1000; i++) {
    typedi.Container.set(i + "", i);
    typedi2.Container.set(i + "", i);
}

function getIndex() {
    return Math.floor(Math.random() * 1000);
}

// add tests
suite
    .add('typedi', function () {
        typedi.Container.get(getIndex() + "");
    })
    .add('perf-20210707', function () {
        typedi2.Container.get(getIndex() + "");
    })
    // add listeners
    .on('cycle', function (event) {
        console.log(String(event.target));
    })
    .on('complete', function () {
        console.log('Fastest is ' + this.filter('fastest').map('name'));
    })
    // run async
    .run({ 'async': true });const Benchmark = require('benchmark');

```

```
typedi x 137,686 ops/sec ±4.46% (75 runs sampled)
perf-20210707 x 4,944,257 ops/sec ±11.93% (61 runs sampled)
Fastest is perf-20210707

```

### CODE REVIEW

**Comment by JerrysShan** [comment]
@NoNameProvided Do you have time to review this PR ?

**Comment by NoNameProvided** [comment]
Hi @JerrysShan! 

Thanks for the contribution. The current development version of the library found on the `develop` branch already contains this change (`container-instance.class.ts`), so I will go ahead and close this.

**Comment by JerrysShan** [comment]
@NoNameProvided Thank you ,when is it expected to be released

**Comment by NoNameProvided** [comment]
It seems like there have been a few significant changes and some of them breaking, I would have to check the changes to make sure nothing breaks. (Tests works, so that I don't expect any major problem.) However I don't know when I will have time, probably can try on the weekend, but no promises.

**Pull request closed without merging**
